const vehiclesData = [
    {
      vehicle: {
        _id: 1,
        category: 'Sedan',
        model: 'Toyota Camry',
        price: 30000,
        rating: 4.5,
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        supply: 50,
      },
      yearlySalesTotal: 200,
      yearlyTotalSoldUnits: 20,
    },
    {
      vehicle: {
        _id: 2,
        category: 'SUV',
        model: 'Honda CR-V',
        price: 35000,
        rating: 4.2,
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        supply: 45,
      },
      yearlySalesTotal: 180,
      yearlyTotalSoldUnits: 18,
    },
    {
      vehicle: {
        _id: 3,
        category: 'Truck',
        model: 'Ford F-150',
        price: 40000,
        rating: 4.0,
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        supply: 40,
      },
      yearlySalesTotal: 150,
      yearlyTotalSoldUnits: 15,
    },
    {
      vehicle: {
        _id: 4,
        category: 'Van',
        model: 'Chevrolet Express',
        price: 45000,
        rating: 4.8,
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        supply: 35,
      },
      yearlySalesTotal: 220,
      yearlyTotalSoldUnits: 22,
    },
    {
      vehicle: {
        _id: 5,
        category: 'Sedan',
        model: 'Nissan Altima',
        price: 32000,
        rating: 4.3,
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        supply: 48,
      },
      yearlySalesTotal: 190,
      yearlyTotalSoldUnits: 19,
    },
    {
      vehicle: {
        _id: 6,
        category: 'SUV',
        model: 'Mazda CX-5',
        price: 37000,
        rating: 4.1,
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        supply: 42,
      },
      yearlySalesTotal: 170,
      yearlyTotalSoldUnits: 17,
    },
    {
      vehicle: {
        _id: 7,
        category: 'Truck',
        model: 'Ram 1500',
        price: 42000,
        rating: 4.2,
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        supply: 38,
      },
      yearlySalesTotal: 160,
      yearlyTotalSoldUnits: 16,
    },
    {
      vehicle: {
        _id: 8,
        category: 'Van',
        model: 'GMC Savana',
        price: 47000,
        rating: 4.7,
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        supply: 33,
      },
      yearlySalesTotal: 200,
      yearlyTotalSoldUnits: 20,
    },
    {
      vehicle: {
        _id: 9,
        category: 'Sedan',
        model: 'Hyundai Sonata',
        price: 33000,
        rating: 4.4,
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        supply: 47,
      },
      yearlySalesTotal: 180,
      yearlyTotalSoldUnits: 18,
    },
    {
      vehicle: {
        _id: 10,
        category: 'SUV',
        model: 'Kia Sportage',
        price: 36000,
        rating: 4.6,
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        supply: 44,
      },
      yearlySalesTotal: 210,
      yearlyTotalSoldUnits: 21,
    },
  ];
  
  export default vehiclesData;
  